"""ime to naziv

Revision ID: 02690c9c6837
Revises: c3dc34a68384
Create Date: 2026-06-02 20:24:03.031050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02690c9c6837'
down_revision = 'c3dc34a68384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clanarine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naziv', sa.String(length=50), nullable=False))
        batch_op.drop_column('ime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clanarine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ime', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('naziv')

    # ### end Alembic commands ###
