"""napravljena tablica clanarine

Revision ID: 262da1514371
Revises: 519ca1a8692f
Create Date: 2026-05-12 20:38:17.034167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262da1514371'
down_revision = '519ca1a8692f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clanarine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('cijena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duzina_trajanja', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clanarine')
    # ### end Alembic commands ###
