"""napravljena tablica treneri

Revision ID: 519ca1a8692f
Revises: 863f4b131ae6
Create Date: 2026-05-12 20:29:50.357942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519ca1a8692f'
down_revision = '863f4b131ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treneri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('specijalizacija', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treneri')
    # ### end Alembic commands ###
