"""Povezana pretplata s clanom i clanarinom

Revision ID: 7d1ba6f32b98
Revises: 262da1514371
Create Date: 2026-05-12 21:13:28.329352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1ba6f32b98'
down_revision = '262da1514371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_pocetka', sa.Date(), nullable=False),
    sa.Column('datum_zavrsetka', sa.Date(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('clanarina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.ForeignKeyConstraint(['clanarina_id'], ['clanarine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pretplate')
    # ### end Alembic commands ###
