"""napravljena tablica clanovi

Revision ID: 863f4b131ae6
Revises: 
Create Date: 2026-05-12 20:21:29.875586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863f4b131ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clanovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobitel', sa.Integer(), nullable=False),
    sa.Column('datum_uclanjenja', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clanovi')
    # ### end Alembic commands ###
