"""dodano

Revision ID: c3dc34a68384
Revises: cbdfd7bb6dd7
Create Date: 2026-05-27 17:31:35.001838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dc34a68384'
down_revision = 'cbdfd7bb6dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treninzi', schema=None) as batch_op:
        batch_op.alter_column('datum',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treninzi', schema=None) as batch_op:
        batch_op.alter_column('datum',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
