"""napravljena tablica treninzi

Revision ID: cbdfd7bb6dd7
Revises: 7d1ba6f32b98
Create Date: 2026-05-13 17:25:11.513801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdfd7bb6dd7'
down_revision = '7d1ba6f32b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treninzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('opis', sa.String(length=50), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('trener_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.ForeignKeyConstraint(['trener_id'], ['treneri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treninzi')
    # ### end Alembic commands ###
